import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//ajout
import { Oswald } from "next/font/google";
import { Header } from "../src/components/header";
//end

import "./globals.css";

//ajout
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});
//end

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable}  antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
